### ISSUE TITLE
Render partials

### ISSUE THREAD

**Issue by n-rodriguez** [faber-lotto/capistrano-template#11]
It would be nice to have a `render` method that would be callable from within templates to render partials (like Rails).

I've implemented it in my project by monkey-patching `capistrano-template` in the `Capfile` like this :

```ruby
module CapistranoRendererPatch
  def render(from, indent: 0, locals: {})
    template = Capistrano::Template::Helpers::PathsLookup.new(fetch(:templating_paths), self).template_file(from)
    content  = Capistrano::Template::Helpers::Renderer.new(template, self, reader: self.reader, locals: self.locals.merge(locals)).as_str
    space    = (indent == 0) ? '' : (' ' * indent)
    content.gsub(/(.*)/, space + '\1')
  end
end

Capistrano::Template::Helpers::Renderer.send(:prepend, CapistranoRendererPatch)
```
Here my `template` directory :

```
config/deploy
└── templates
    └── shared
        ├── nginx
        │   ├── back.conf.erb
        │   ├── common.conf.erb
        │   ├── front.conf.erb
        ├── nginx.conf.erb
```

In a Capistrano task I have :

```ruby
namespace :config do
  desc 'Generate configuration files'
  task :generate do
    on roles(:app) do |host|
      template 'nginx.conf', "#{shared_path}/config/nginx.conf"
    end
  end
end
```

Then in `nginx.conf` file :

```
<%= render 'nginx/common.conf' %>
<%= render 'nginx/back.conf' %>
<%= render 'nginx/front.conf' %>
```

Thank you!

**Comment by slowjack2k** [comment]
It has taken some while, but now I did implement this feature. Maybe you can test the branch "feature/11_render_partials" before I merge it into master.

**Comment by n-rodriguez** [comment]
> Maybe you can test the branch "feature/11_render_partials" before I merge it into master.

I'll try this week! Thank you!

**Comment by slowjack2k** [comment]
Released new gem version. Please reopen in case some thing went wrong.

**Comment by n-rodriguez** [comment]
> Released new gem version. Please reopen in case some thing went wrong.

Thank you! I've just tested it and it works perfectly 👍
