### ISSUE TITLE
undefined method `template' for #<SSHKit::Backend::Printer in dry-run mode

### ISSUE THREAD

**Issue by merrykju** [faber-lotto/capistrano-template#13]
When running `[bundle exec] cap staging define_usermacros  -n --trace` capistrano tells me that the template method is unknown to `SSHKit::Backend::Printer`:

`** Invoke staging (first_time)`
`** Execute staging`
`** Invoke load:defaults (first_time)`
`** Execute load:defaults`
`** Invoke define_usermacros (first_time)`
`** Execute define_usermacros`
`cap aborted!`
`SSHKit::Runner::ExecuteError: Exception while executing as    deploy@10.33.66.12: undefined method 'template' for #<SSHKit::Backend::Printer:0x007ff383bd4d80>`
`/usr/local/var/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/sshkit-1.13.1/lib/sshkit/runners/parallel.rb:15:in 'rescue in block (2 levels) in execute'`
`/usr/local/var/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/sshkit-1.13.1/lib/sshkit/runners/parallel.rb:11:in 'block (2 levels) in execute'`
`NoMethodError: undefined method 'template' for #<SSHKit::Backend::Printer:0x007ff383bd4d80>
config/deploy.rb:42:in 'block (2 levels) in <top (required)>'`
`/usr/local/var/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/sshkit-1.13.1/lib/sshkit/backends/abstract.rb:29:in 'instance_exec'`
`/usr/local/var/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/sshkit-1.13.1/lib/sshkit/backends/abstract.rb:29:in 'run'
/usr/local/var/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/sshkit-1.13.1/lib/sshkit/runners/parallel.rb:12:in 'block (2 levels) in execute'`
`Tasks: TOP => define_usermacros`

The task runs fine when run for real (i.e. without -n).

Here's my task:

`[...]`
`desc 'Upload user macros as rendered erb-template'`
`task :define_usermacros do`
`  on roles :all do`
`    template 'resource.cfg', "#{release_path}/resource_file",`
`         0o640,`
`         locals: {`
`           'user1' => 'blah'`
 `        }`
` end`
`end`

And here my environment:

`Ruby     ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-darwin15]`
`Rubygems 2.6.10`
`Bundler  1.14.3`

Gem versions:

`capistrano          3.7.2  (update available)`
`airbrussh           1.2.0`
`rake                12.0.0`
`sshkit              1.13.1`
`net-ssh             4.1.0`
`capistrano-template 0.0.8`

**Comment by slowjack2k** [comment]
Can you please try to add 

```ruby     
       require 'sshkit/backend/printer'
       SSHKit::Backend::Printer.send(:include, Capistrano::Template::Helpers::DSL)
```

after `require 'capistrano/capistrano_plugin_template'` ? Does this solve your issue?

**Comment by merrykju** [comment]
SSHKit::Backend::Printer.send(:include, Capistrano::Template::Helpers::DSL)
did the job, thnx!

**Comment by slowjack2k** [comment]
I did release a new gem version. You no longer need to include previous 2 lines inside your capfile. Please reopen this issue if the failure still exists.
