### ISSUE TITLE
Add custom variables

### ISSUE THREAD

**Issue by czerasz** [faber-lotto/capistrano-template#3]
Usage:

```
template "unicorn_init.erb", "/tmp/unicorn_init", 0770, {test: true}
```

`test` could be used in the template. This would allow one to change the template behavior per role. Would make it more dynamic.

**Comment by slowjack2k** [comment]
Thanks for your suggestion, I will consider it. Or maybe you can provide a PR.

**Comment by czerasz** [comment]
Nice, thx a lot!
