### ISSUE TITLE
Set file owner

### ISSUE THREAD

**Issue by beedaan** [faber-lotto/capistrano-template#7]
It's a pretty nice feature to be able to set the mode of the file uploaded to the host.  I want to be able to set the owner as well.  I thought about using the `as()` block to run the command as a separate user, but I realized I could only do that as users in the sudoers file.

The use case I'm working on is uploading config files for tomcat.  I'd like the file owner to be tomcat, but tomcat is not a sudo user.  Right now my solution is to `execute chown tomcat <file>` after the file is uploaded.  Is this the preferable way?  I think it would be a nice feature to set the file owner.

**Comment by slowjack2k** [comment]
At the moment your solution is the only way. Maybe I will have the opportunity to extend this gem for changing the owner too.

**Comment by slowjack2k** [comment]
I did at file owner support to the master branch. Keep in mind that `chown ` needs `sudo ` rights. Please reopen this issue when anything goes wrong.
