### ISSUE TITLE
Support within() block

### ISSUE THREAD

**Issue by beedaan** [faber-lotto/capistrano-template#8]
It would be awesome to use the current working directory set in `within()` blocks.  Right now it only uses the absolute path.

This is the syntax I am thinking of
```ruby
within host.properties.tomcat[:home] do
  template 'setenv.sh', './bin/setenv.sh', 0755
end
```
Currently that would put my file in `~/bin/setenv.sh`

**Comment by slowjack2k** [comment]
I did at support for `within` block to the master branch. Please reopen this issue when anything goes wrong.
